name: Build Docker image

on: [push, pull_request]

jobs:
  build-and-testvariants:
    name: Build image variants and run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { variant: 'apache', test-files: ['apache-postgres'], docker-tag: 'roundcube-test-apache' }
          - { variant: 'fpm', test-files: ['fpm-postgres'], docker-tag: 'roundcube-test-fpm' }
          - { variant: 'fpm-alpine', test-files: ['fpm-postgres'], docker-tag: 'roundcube-test-fpm-alpine' }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get docker hub username
        id: creds
        run: echo '::set-output name=username::${{ secrets.DOCKER_PULL_USERNAME }}'
      - name: Login to Docker Hub
        if: steps.creds.outputs.username != ''
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_PULL_USERNAME }}
          password: ${{ secrets.DOCKER_PULL_PASSWORD }}
      - name: Build image variant "${{ matrix.variant }}"
        run: cd ${{ matrix.variant }} && docker buildx build \
        --platform linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x \
        --push \
        ./ -t ${{ matrix.docker-tag }}
      - name: Run tests
        env:
          ROUNDCUBEMAIL_TEST_IMAGE: ${{ matrix.docker-tag }}
        run: |
          set -exu;
          for testFile in ${{ join(matrix.test-files, ' ') }};
          do
            docker-compose -f ./tests/docker-compose.test-${testFile}.yml \
            up --exit-code-from=sut --abort-on-container-exit
          done

### do it with docker compose  instead
#https://github.com/roundcube/roundcubemail-docker/blame/master/.github/workflows/build.yml


          		